// hr-frontend-ng/src/app/app.component.ts
import {Component} from '@angular/core';
import {Employee} from "../model/employee";
import {EmployeeService, EmployeeStatusResponse} from "../services/employee_service";

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
  providers: [EmployeeService]
})
export class AppComponent {
  private employee: Employee;
  private employees: Array<Employee>;

  constructor(private empsrv: EmployeeService) {
    this.employee = new Employee(
      "",
      "Test User",
      "TR",
      10000,
      1973,
      "IT",
      true,
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAMAAAD04JH5AAABC1BMVEX///8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADXsw3hAAAAWXRSTlMAWQFYVwIlVUpSTypIR0wSKBFFAw9WCRo/OgUvQjMNIR5EBhBOLiIZExRTCjsdDlBBHD1UQwc4Sx8wQC0kKxtGBAwsPDEnMhU0N00gOSlJNSYjURY+CxcINmo6xHsAAATwSURBVHhe7Ztnbxs5EIbfGXK16l22VSwXufcax70kju30enf//5ccJDsXCPJyaK3I4BA/XwQLEN6Hs/SSw5Xwf+IZZnSZ7YwnmncTM8l0KtSKSIepuWyr/qa4vvQ3ujCzk3gAaE/dlr9SJCvZ99fLjZ6Di/jCcU5TD9WFegy+kV6bWh21AwMXX8oPSWTgQSPcWa8APML4RibdSycbehJvM/ujUmDgZHMgXXZYuWqAeRTxSzkiTU9FE21OxS9CADQN8ZLC0VhMA0Y7S6RoSBSF07GKwJjWwvDFIkwOb8DAqTB8GUUzswiGzT+k+GhKtxEMlz9JaiQGu6VhDOR8e4NwCANGU8i3R9FKG/zU/CKNDkVvG08zCLBNo0TT1lPvPzVSNEIUXT2tBDlSNGKW7A0YxyPPV5SDfX5V0chRlEBgK7BDDgwoXbHNXyIXKLpGYCfw3qoASvXvBGUO2C5/NSSJB0OdSs9t7j68IaJoHGwj8JmURXzy7uTb5X4luBgrvXydUxYKiup2Ai1SUnx6voQ+Nk7zFgqpWVgwFkoD0R8qALgLgJ8vX76Skq+BBdukzPn5DhAw+uAAaKyJpXsNCw6NAor2AgQRG+hJyb0MC7ZIGbd4QBDZQgg1sJoEwZxxDHOGhZ3BScGgAJFLLaxpgUEey8IkmIbIN2MBjk35AKNuvoAZiEyRis7PM4wwbqRbkcipSeCluJzwAZlIQuQ2UkBZfJxxZ5yGNYjUDQKfwaJAwihAsW4D4aqFwCIZgUg2SkDREUQYhbgCedP/EMsCGzqmQJoiWbQRaBsFQoisUBSqGr8CWxAJKYrdMRuBEsW8E973ZGoATal9G4HtuDsSiuaHhYB5TxCuQuQgf5BMfsxmc7nzcnlmb6/V2jqamPi+82qnvioLIMibCnAOGY5z2s4YFxbTJ8J92AhMkBL2Iy5h3IgNcnzknkJYzNwR4CUpoS9xCWM/ZbwCTQRwijADwzhH5/FPFhXNOy0AM67JyGbDZQEYuBJagimXBQgQ1IX8FhzCuJR6slob7C4e6yFpMvIOgbt8niSpL58HO4tHJ0tmFN26nP0fiLSQ/wlgV/HVsnw4degwPyMPn4qu8gOMzUjD16TPwHCUX1ghTUJ+vupqBWBs1OTyr1Xc5V/MieWnBMAOF38tDD9bBbvKD5AhJQy/6XD4jI509ZPLAMMdM6SMw59nl/EsbH8pWwIYLjEs/4po0nE8Y9uYv+A4H4zvhrO82l9gx/mGhyqKwoLz9oOxbrgCy87zwXgTLTDtPh+MPVKRD4UY7qmkDcf57gUYP3T0AxGGB4FlQwE8wBh/fApomocPA45+qnPjSSBBSjiCcSxQJCU8F3UskIkQeAH2I3AaIdAE+6pATQ1So6IvgXl6FH8CheJJYpCTYhWMPwOOAn8czzzzeyf/r2D8DgcGUKmeLSQWzjoVAOw/f/HFHN2Tfj8OsO/4XN+vaz6e+VRg4FM3vO/LlS/YmwGDW//F/1IoB74MGK9IP7Ipn/BWgIVe/qBBwlMJgrcRfcHmhZ8CLEb2xtt+WsOriCNSTYd+BD51BeTGwP/5iKJ/wL+zNdRU9COwQVGUwN7uQ4NoOvLVmFxqUo+dkPpqTBjrRGow/53H1Wi6bzG8/2PK63rcOX+I/fmSLYDhDwbendMvcsIBuRMDlD6sfUztppKvMgUMnf/Mv8NIVU+cyYl6AAAAAElFTkSuQmCC"
    )
  }

  get totalSalary(): number {
    return this.employees
      .reduce((sum, emp) => sum + Number(emp.salary), 0);
  }

  get averageSalary(): number {
    return this.totalSalary / this.employees.length;
  }

  findAll() {
    this.empsrv.findAllEmployees()
      .subscribe((employees) => {
        this.employees = employees;
      })
  }

  findEmployee() {
    this.empsrv
      .findEmployee(this.employee.identityNo)
      .subscribe(employee =>
        this.employee = employee);
  }

  addEmployee() {
    this.empsrv.addEmployee(this.employee)
      .subscribe((status) => {
        console.log("Employee is added!");
        this.findAll();
      });
  }

  updateEmployee() {
    this.empsrv.updateEmployee(this.employee)
      .subscribe((status) => {
        console.log("Employee is updated!")
        this.findAll();
      });
  }

  removeEmployee() {
    this.empsrv.removeEmployee(this.employee.identityNo)
      .subscribe((employee) => {
        console.log("Employee is removed!")
        this.findAll();
        this.employee = employee;
      });
  }

  copyEmployee(emp: Employee) {
    this.employee = emp;
  }

  readPhoto(e) {
    let reader : FileReader = new FileReader();
    reader.onload = (e) => {
      this.employee.photo = reader.result as string;
    };
    reader.readAsDataURL(e.target.files[0]);
  }

  deleteEmployee(emp: Employee) {
    this.empsrv.removeEmployee(emp.identityNo)
      .subscribe((employee) => {
        console.log("Employee is removed!")
        this.findAll();
        this.employee = employee;
      });
  }
}

<p>
<div id="app" class="container">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <div class="row">
        <div class="col-md-10">
          <h3 class="panel-title">Employee Panel</h3>
        </div>
      </div>
    </div>
    <div class="panel-body">
      <div class="form-group">
        <label for="identityNo">Identity No</label>
        <input type="text" id="identityNo"
               [(ngModel)]="employee.identityNo"
               class="form-control">
      </div>
      <div class="form-group">
        <label for="fullName">Fullname</label>
        <input type="text" id="fullName"
               [(ngModel)]="employee.fullname"
               class="form-control">
      </div>
      <div class="form-group">
        <label for="salary">Salary</label>
        <input type="text" id="salary"
               [(ngModel)]="employee.salary"
		           class="form-control">
      </div>
      <div class="form-group">
        <label for="birthYear">Birth Year</label>
        <input type="text" id="birthYear"
               [(ngModel)]="employee.birthYear"
               class="form-control">
      </div>
      <div class="form-group">
        <label for="iban">IBAN</label>
        <input type="text" id="iban"
               [(ngModel)]="employee.iban"
		           class="form-control">
      </div>
      <div class="form-group">
        <label for="department">Department</label>
        <select id="department"
                [(ngModel)]="employee.department"
                class="form-control">
          <option>IT</option>
          <option>Finance</option>
          <option>Sales</option>
          <option>HR</option>
        </select>
      </div>
      <div class="form-group">
        <label for="photo">Photo</label>
        <img id="photoImage"
             [src]="employee.photo"
             style="width: 64px; height: 64px;">
        <label class="btn btn-info btn-file">
          <input type="file"
                 (change)="readPhoto($event)"
                 id="photo" style="display: none;">
          <span>Browse</span>
        </label>
      </div>
      <div class="form-group">
        <button (click)="addEmployee()"
                class="btn btn-info">Add</button>
        <button (click)="updateEmployee()"
                class="btn btn-warning">Update</button>
        <button (click)="removeEmployee()"
                class="btn btn-danger">Remove</button>
        <button class="btn btn-success"
                (click)="findEmployee()">Find</button>
        <button class="btn btn-success"
                (click)="findAll()">Find All</button>
      </div>
    </div>
  </div>
  <div class="panel panel-success">
    <div class="panel-heading">
      <div class="row">
        <div class="col-md-11">
          <h3 class="panel-title">Employees</h3>
        </div>
      </div>
    </div>
    <div class="panel-body">
      <table class="table table-responsive">
        <thead>
        <tr>
          <th>No</th>
          <th>Photo</th>
          <th>Identity No</th>
          <th>Full name</th>
          <th>Salary</th>
          <th>Iban</th>
          <th>Department</th>
          <th>Birth Year</th>
          <th>Operations</th>
        </tr>
        </thead>
        <tbody>
        <tr *ngFor="let emp of employees; let i= index;"
            (mouseenter)="copyEmployee(emp)">
          <td>{{i+1}}</td>
          <td><img  [src]="emp.photo"
                    style="width: 32px; height: 32px; border-radius: 16px;"></td>
          <td>{{emp.identityNo}}</td>
          <td>{{emp.fullname}}</td>
          <td>{{emp.salary}}</td>
          <td>{{emp.iban}}</td>
          <td>{{emp.department}}</td>
          <td>{{emp.birthYear}}</td>
          <td>
            <button class="btn btn-danger"
                    (click)="deleteEmployee(emp)">Delete</button>
          </td>
        </tr>
        <tr>
          <td colspan="3"></td>
          <td>Total Salary</td>
          <td colspan="5">{{totalSalary | currency:'TL'}}</td>
        </tr>
        <tr>
          <td colspan="3"></td>
          <td>Total Salary</td>
          <td colspan="5">{{averageSalary | currency:'TL'}}</td>
        </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

// hr-frontend-react/src/App.js
import React, {Component} from 'react';
import './App.css';
import {Employee} from "./model/employee";

/**
 * @author Binnur Kurt <binnur.kurt@gmail.com>
 */
class App extends Component {
    constructor(props) {
        super(props);
        this.state = {
            employees: [],
            totalSalary: NaN,
            averageSalary: NaN,
            employee: new Employee()
        }
        this.findAll = this.findAll.bind(this);
        this.findEmployee = this.findEmployee.bind(this);
        this.handleChange = this.handleChange.bind(this);
        this.addEmployee = this.addEmployee.bind(this);
        this.updateEmployee = this.updateEmployee.bind(this);
        this.removeEmployee = this.removeEmployee.bind(this);
        this.removeRow = this.removeRow.bind(this);
        this.getJson = this.getJson.bind(this);
        this.readPhoto = this.readPhoto.bind(this);
    }

    getJson() {
        return JSON.stringify(this.state.employee);
    }

    addEmployee() {
        fetch('http://localhost:4001/employees',
            {
                method: 'post', body: this.getJson(), headers: {
                    "Accept": "application/json", "Content-Type": "application/json"
                }
            })
            .then(res => res.json())
            .then(res => this.findAll());
    }

    updateEmployee() {
        fetch('http://localhost:4001/employees', {
            method: 'put', body: this.getJson(), headers: {
                "Accept": "application/json",
                "Content-Type": "application/json"
            }
        })
            .then(res => res.json())
            .then(res => this.findAll());
    }

    removeEmployee() {
        fetch('http://localhost:4001/employees/' + this.state.employee.identityNo, {method: 'delete'})
            .then(emp => emp.json())
            .then(emp => {
                this.setState({employee: emp});
                this.findAll();
            });
    }

    removeRow(emp) {
        fetch('http://localhost:4001/employees/' + emp.identityNo, {method: 'delete'})
            .then(e => e.json())
            .then(e => {
                this.setState({employee: e})
                this.findAll();
            });
    }

    handleChange(event) {
        const target = event.target;
        const value = target.value;
        const name = target.name;
        let emp = this.state.employee;
        emp[name] = value;
        this.setState({
            employee: emp
        });
    }

    findEmployee() {
        fetch('http://localhost:4001/employees/' + this.state.employee.identityNo)
            .then(emp => emp.json())
            .then(emp => this.setState({employee: emp}))
    }

    findAll() {
        fetch('http://localhost:4001/employees')
            .then(employees => employees.json())
            .then(employees => {
                let totalSalary = employees.reduce((sum, emp) => sum + Number(emp.salary), 0);
                let averageSalary = totalSalary / employees.length;
                this.setState({employees: employees, totalSalary: totalSalary, averageSalary: averageSalary});
            });
    }

    readPhoto(files) {
        let reader = new FileReader();
        reader.onload = (e) => {
            this.state.employee.photo = e.target.result;
            this.setState({employee: this.state.employee});
        };
        reader.readAsDataURL(files[0]);
    }

    render() {
        return (
            <div>
                <p></p>
                <div className="container">
                    <div className="panel panel-primary">
                        <div className="panel-heading">
                            <div className="row">
                                <div className="col-md-10">
                                    <h3 className="panel-title">Employee Panel</h3>
                                </div>
                            </div>
                        </div>
                        <div className="panel-body">
                            <div className="form-group">
                                <label htmlFor="identityNo">Identity No</label>
                                <input type="text" id="identityNo"
                                       onChange={this.handleChange}
                                       name="identityNo"
                                       value={this.state.employee.identityNo}
                                       className="form-control"></input>
                            </div>
                            <div className="form-group">
                                <label htmlFor="fullName">Fullname</label>
                                <input type="text" id="fullName"
                                       value={this.state.employee.fullname}
                                       name="fullname"
                                       onChange={this.handleChange}
                                       className="form-control"></input>
                            </div>
                            <div className="form-group">
                                <label htmlFor=" salary">Salary</label>
                                <input type="text" id="salary"
                                       name="salary"
                                       onChange={this.handleChange}
                                       value={this.state.employee.salary}
                                       className="form-control"></input>
                            </div>
                            <div className="form-group">
                                <label htmlFor="birthYear">Birth Year</label>
                                <input type=" text" id="birthYear"
                                       name="birthYear"
                                       onChange={this.handleChange}
                                       value={this.state.employee.birthYear}
                                       className="form-control"></input>
                            </div>
                            <div className="form-group">
                                <label htmlFor="iban">IBAN</label>
                                <input type="text" id="iban"
                                       name="iban"
                                       onChange={this.handleChange}
                                       value={this.state.employee.iban}
                                       className="form-control"></input>
                            </div>
                            <div className="form-group">
                                <label htmlFor="department">Department</label>
                                <select id="department"
                                        onChange={this.handleChange}
                                        name="department"
                                        value={this.state.employee.department}
                                        className="form-control">
                                    <option>IT</option>
                                    <option>Finance</option>
                                    <option>Sales</option>
                                    <option>HR</option>
                                </select>
                            </div>
                            <div className=" form-group">
                                <label htmlFor="photo">Photo</label>
                                <img id="photoImage"
                                     alt={''}
                                     src={this.state.employee.photo}
                                     className="photo"></img>
                                <label className="btn btn-info btn-file">
                                    <input type="file"
                                           id="photo"
                                           onChange={(e) => this.readPhoto(e.target.files)}
                                           className="hide"></input>
                                    <span>Browse</span>
                                </label>
                            </div>
                            <div className="form-group">
                                <button onClick={this.addEmployee}
                                        className="btn btn-info">Add
                                </button>
                                <button onClick={this.updateEmployee}
                                        className="btn btn-warning">Update
                                </button>
                                <button onClick={this.removeEmployee}
                                        className="btn btn-danger">Remove
                                </button>
                                <button onClick={this.findEmployee}
                                        className="btn btn-success">Find
                                </button>
                                <button onClick={this.findAll}
                                        className="btn btn-success">Find All
                                </button>
                            </div>
                        </div>
                    </div>
                    <div className="panel panel-primary">
                        <div className="panel-heading">
                            <div className="row">
                                <div className="col-md-10">
                                    <h3 className="panel-title">Employees</h3>
                                </div>
                            </div>
                        </div>
                        <div className="panel-body">
                            <table className="table table-responsive">
                                <thead>
                                <tr>
                                    <th>No</th>
                                    <th>Photo</th>
                                    <th>Identity No</th>
                                    <th>Full name</th>
                                    <th>Salary</th>
                                    <th>Iban</th>
                                    <th>Department</th>
                                    <th>Birth Year</th>
                                    <th>Operations</th>
                                </tr>
                                </thead>
                                <tbody>
                                {this.state.employees.map(
                                    (emp, i) =>
                                        <tr key={i}>
                                            <td>{i + 1}</td>
                                            <td><img src={emp.photo}
                                                     alt={''}
                                                     className="circularphoto"></img></td>
                                            <td>{emp.identityNo}</td>
                                            <td>{emp.fullname}</td>
                                            <td>{emp.salary}</td>
                                            <td>{emp.iban}</td>
                                            <td>{emp.department}</td>
                                            <td>{emp.birthYear}</td>
                                            <td>
                                                <button onClick={() => this.removeRow(emp)}
                                                        className="btn btn-danger">Delete
                                                </button>
                                            </td>
                                        </tr>
                                )}
                                <tr>
                                    <td colSpan={3}></td>
                                    <td>Total Salary:</td>
                                    <td colSpan={5}>{this.state.totalSalary.toFixed(2)}</td>
                                </tr>
                                <tr>
                                    <td colSpan={3}></td>
                                    <td>Average Salary:</td>
                                    <td colSpan={5}>{this.state.averageSalary.toFixed(2)}</td>
                                </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        );
    }
}

export default App;
