// world-react/src/App.js
import {useEffect, useState} from "react";


function App() {
  const [continents, setContinents] = useState([]);
  const [continent, setContinent] = useState("Asia");
  const [countries, setCountries] = useState([]);
  let list = () => {
    fetch(`http://localhost:9100/world/api/v1/countries?continent=${continent}`,{
      method: "GET",
      headers: {
        "Accept": "application/json"
      }
    }).then( res => res.json())
        .then( countries => setCountries(countries));
  }
  let handleChange = (event) => {
    setContinent(event.target.value);
  }
  useEffect(() => {
    fetch("http://localhost:9100/world/api/v1/continents",{
      method: "GET",
      headers: {
        "Accept": "application/json"
      }
    }).then( res => res.json())
      .then( continents => setContinents(continents));
    return () => {}
  }, []);
  return (
      <div className="container">
        <p></p>
        <div className="card">
          <div className="card-header">
            <h4 className="card-title">World Card</h4>
          </div>
          <div className="card-body">
            <label className="form-label" htmlFor="continent">Continent:</label>
            <select name="continent"
                    onChange={handleChange}
                    className="form-select"
                    id="continent">
              {
                continents.map( continent => <option key={continent}>{continent}</option>)
              }
            </select>
            <button onClick={list} className="btn btn-success">List</button>
          </div>
        </div>
        <p></p>
        <div className="card">
          <div className="card-header">
            <h4 className="card-title">World Countries</h4>
            <p></p>
            <span className="badge bg-danger" data-bind="text: population"></span>
          </div>
          <div className="card-body">
            <table className="table table-bordered table-hover table-striped table-responsive">
              <thead>
              <tr>
                <th>No</th>
                <th>Name</th>
                <th>Population</th>
                <th>Surface Area</th>
                <th>GNP</th>
                <th>Independence Year</th>
                <th>Government Form</th>
              </tr>
              </thead>
              <tbody>
              {
                countries.map( (country,index) =>
                    <tr key={country._id}>
                      <td>{index + 1}</td>
                      <td>{country.name}</td>
                      <td>{country.population}</td>
                      <td>{country.surfaceArea}</td>
                      <td>{country.gnp}</td>
                      <td>{country.indepYear}</td>
                      <td>{country.governmentForm}</td>
                    </tr>
                )
              }
              </tbody>
            </table>
          </div>
        </div>
      </div>
  );
}

export default App;

// world-ng/src/app/app.component.ts
import {Component, OnInit} from '@angular/core';
import {WorldService} from "../services/world-service";
import {Country} from "../model/country";
import {HttpClient} from "@angular/common/http";

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {
  public continents: Array<String> = [];
  public countries: Array<Country> = [];
  public continent: String = "Asia"

  constructor(private worldService: WorldService) {
  }

  list() {
    this.worldService.getCountriesByContinent(this.continent).subscribe(countries => this.countries = countries);
  }

  ngOnInit(): void {
    this.worldService.getContinents().subscribe(continents => this.continents = continents);
  }
}

<div class="container">
  <p></p>
  <div class="card">
    <div class="card-header">
      <h4 class="card-title">World Card</h4>
    </div>
    <div class="card-body">
      <label class="form-label" for="continent">Continent:</label>
      <select [(ngModel)]="continent" class="form-select" id="continent">
        <option *ngFor="let cont of continents" [ngValue]="cont">{{cont}}</option>
      </select>
      <button (click)="list()" class="btn btn-success">List</button>
    </div>
  </div>
  <p></p>
  <div class="card">
    <div class="card-header">
      <h4 class="card-title">World Countries</h4>
      <p></p>
      <span class="badge bg-danger" data-bind="text: population"></span>
    </div>
    <div class="card-body">
      <table class="table table-bordered table-hover table-striped table-responsive">
        <thead>
        <tr>
          <th>No</th>
          <th>Name</th>
          <th>Population</th>
          <th>Surface Area</th>
          <th>GNP</th>
          <th>Independence Year</th>
          <th>Government Form</th>
        </tr>
        </thead>
        <tbody data-bind="foreach: {data: countries, as: 'country'}">
        <tr *ngFor="let country of countries;index as i">
          <td>{{i+1}}</td>
          <td>{{country.name}}</td>
          <td>{{country.population}}</td>
          <td>{{country.surfaceArea}}</td>
          <td>{{country.gnp}}</td>
          <td>{{country.indepYear}}</td>
          <td>{{country.governmentForm}}</td>
        </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>
